# Generated by Django 5.2.5 on 2025-09-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='params',
        ),
        migrations.AddField(
            model_name='report',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
