# Generated by Django 5.2.5 on 2025-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='symbol',
            field=models.CharField(default='BTCUSDT', max_length=50),
            preserve_default=False,
        ),
    ]
