# Generated by Django 5.2.5 on 2025-09-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_params_report_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
