# Generated by Django 5.2.5 on 2025-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
