# Generated by Django 5.2.5 on 2025-09-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sell_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('buy_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bought_at', models.DateTimeField()),
                ('sold', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
