# Generated by Django 5.2.5 on 2025-08-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_processedevent_purchaselot_trade_purchase_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaselot',
            name='remaining_amount',
        ),
        migrations.AddField(
            model_name='purchaselot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
