# Generated by Django 5.2.5 on 2025-08-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_remove_purchaselot_remaining_amount_and_more'),
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='purchase_lot',
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('buy_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trades.lot'),
        ),
        migrations.DeleteModel(
            name='PurchaseLot',
        ),
    ]
