# Generated by Django 5.2.5 on 2025-09-02 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_remove_trade_purchase_lot_lot_trade_lot_and_more'),
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='profit',
        ),
        migrations.AddField(
            model_name='lot',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='trade',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lot', to='trades.trade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='side',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4),
        ),
    ]
