# Generated by Django 5.2.5 on 2025-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_remove_lot_amount_remove_lot_buy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
