# Generated by Django 5.2.5 on 2025-09-03 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_lot_profit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sell_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lot',
            name='trade',
        ),
        migrations.DeleteModel(
            name='ProcessedEvent',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='timestamp',
            new_name='bought_at',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='side',
        ),
        migrations.AddField(
            model_name='trade',
            name='buy_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='trade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='trades.trade'),
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
