# Generated by Django 5.2.5 on 2025-09-03 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_sale_remove_lot_trade_delete_processedevent_and_more'),
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='users.profile'),
        ),
    ]
