# Generated by Django 5.2.5 on 2025-09-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_alter_trade_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sold_at',
        ),
    ]
